Samples/OpenCVSample/OpenCVSample.Interop/OpenCVSample.Interop.vcxproj
Samples/OpenCVSample/OpenCVSample/OpenCVSample.csproj

The README file is one level above and common to both projects. Markdown is not required to be referenced in the project files.

OpenCVSample : VS warns readme doesnt exist. removing reference from csproj and vcxproj.

---

Samples/LinuxSpeechSample/Program.cs
Samples/LinuxSpeechSample/build.sh
Samples/RosTurtleSample/build.sh
Sources/Media/Microsoft.Psi.Media.Native.x64/build.sh
build.sh

Fixed the building process of the code base
- Check if FFMPEGDir exists and only build it if it does.
- Fixed misspelling of one of the packages.
- Added LinuxSpeechSample to the build chain.
- Added ability to specify the audio device in the LinuxSpeechSample.
- Feel free to copy and paste the instructions to build on Linux from here:
https://github.com/xiangzhi/RosBag2PsiStoreConverter/wiki/Installing-and-%5CPsi-Codebase-on-Ubuntu-18.04
Remaining Problem
- I wasn't able to get the LinuxSpeechSample to work, the audio capture only capture garbage. It might be a setting problem.

Better linux build chain

---

Sources/Visualization/Microsoft.Psi.Visualization.Common.Windows/Views/VisualizationContainerView.xaml

Made DataGrid view in VisualizationContainerView read-only so that it does not attempt to respond to mouse click routed events which bubble up. Fixes #71

Fix PsiStudio 3D Visualization crash

---

Sources/Tools/PsiStudio/Microsoft.Psi.PsiStudio/MainWindowViewModel.cs

When PsiStudio starts up, if the user has 3rd party assemblies specified and classes within them are used in the current layout, PsiStudio will attempt to load the layout before the 3rd party assemblies have finished loading. This causes an error which we attempt to display in a dialog window, we get an unhandled exception because we're trying to set the parent window of the dialog to the main window, but the main window has not yet been rendered.
Updated the code so that when setting the CurrentLayout property, we don't try to load the layout if we've not yet finished initializing.  Once the MainWindow has been shown, we then attempt to open the current layout and everything succeeds.

Fixed bug where loading layout at startup sometimes crashed

---

Sources/Visualization/Microsoft.Psi.Visualization.Windows/Navigation/Navigator.cs

When switching layouts, we now preserve the button states in PsiStudio for the following settings:
Show Absolute Timing
Show Timing Relative To Session Start
Show Timing Relative To Selection Start
Cursor Follows Mouse
I believe this constitutes all of the toolbar button settings that need to be preserved when we create a new Navigator on layout change.

Preserve timing button states when switching layouts

---

Sources/Calibration/Microsoft.Psi.Calibration/CameraIntrinsics.cs
Sources/Visualization/Microsoft.Psi.Visualization.Windows/VisualizationObjects/SpatialDepthCameraViewAsPointCloudVisualizationObject.cs

- The constructor for `CameraIntrinsics` now checks for a valid 3x3 transform matrix. Radial distortion coefficients are initialized as a vector of length 6, copying over however many are passed to the constructor. Same for tangential distortion coefficients (but length=2).
Fixes #107 
- Fixed a small bug in `SpatialDepthCameraViewAsPointCloudVisualizationObject` to not allow the Point Cloud Sparsity property to take any value lower than 1.

bug fixes to camera intrinsics and depth camera view as point cloud viz

---

Sources/Integrations/Onnx/Test.Psi.Onnx/TinyYoloV2Tester.cs

Currently, the TinyYoloV2Test would have succeeded even if the PsiTestResources variable was not set and nothing was ran. This pull request change it such that it reports inconclusive, similar to the Onnx.ImageNet tests.

Change Console.Writeline to Assert.Inconclusive

---

Sources/Integrations/ROS/Microsoft.Psi.ROS/RosMessage.fs

The `NewStructDef()` constructors generated by F# works in C# (e.g. `RosMessage.RosFieldDef.NewStructDef(someMessageDef.Fields)`) but requires referencing `FSharp.Core`. This change adds a `CreateStructDef(...)` constructor taking the `MessageDef` directly (e.g. `RosMessage.CreateStructDef(someMessageDef)`), as well as a `CreateStructVal(...)` constructor and constructors for `Variable/FixedArrayVal`.

Added helper for constructing `StructDefs` from C#

---

Sources/Integrations/ROS/Microsoft.Psi.ROS/RosMessage.fs

This PR fixes a bug where when converting `DateTime` to `Time` in ROS, the `nsec` of Time was converted to microsecond (10e-6) instead of nanoseconds (10e-9)

Fix bug in nanosecond conversion in ROS component.

---

Sources/Integrations/CognitiveServices/Microsoft.Psi.CognitiveServices.Face/PersonGroup.cs

If the training status is TrainingStatusType.Failed, it may cause an endless loop.

Fixed a bug in creating person groups

---

Sources/Visualization/Microsoft.Psi.Visualization.Windows/Navigation/Navigator.cs
Sources/Visualization/Microsoft.Psi.Visualization.Windows/Views/VisualizationPanelView.cs

Fixes an issue where captured cursor time is sometimes incorrect due to the cursor jumping to the current position if the Copy Cursor Time to Clipboard context menu item is clicked while over a timeline panel.

Capture cursor time when menu item is created

---

Sources/MixedReality/Microsoft.Psi.MixedReality.UniversalWindows/PhotoVideoCamera.cs

Small fix to re-create the HoloLens PhotoVideoCamera's `CameraIntrinsics` every frame, rather than just once and caching, because parameters might change over time (particularly focal length being changed due to auto-focus).

PhotoVideoCamera Intrinsics per Frame

---

Sources/Audio/Microsoft.Psi.Audio.Windows/AudioCapture.cs
Sources/Integrations/MicrosoftSpeech/Microsoft.Psi.MicrosoftSpeech.Windows/MicrosoftSpeechIntentDetector.cs
Sources/Integrations/MicrosoftSpeech/Microsoft.Psi.MicrosoftSpeech.Windows/MicrosoftSpeechRecognizer.cs
Sources/MixedReality/HoloLensCapture/HoloLensCaptureExporter/DataExporter.cs
Sources/MixedReality/HoloLensCapture/HoloLensCaptureExporter/Operators.cs
Sources/Runtime/Microsoft.Psi/Common/DeliveryPolicy.cs
Sources/Runtime/Microsoft.Psi/Common/DeliveryPolicy{T}.cs
Sources/Runtime/Microsoft.Psi/Components/Zip.cs
Sources/Runtime/Microsoft.Psi/Executive/Pipeline.cs
Sources/Runtime/Microsoft.Psi/Streams/DeliveryQueue.cs
Sources/Runtime/Microsoft.Psi/Streams/Receiver{T}.cs
Sources/Runtime/Test.Psi/DeliveryPolicyTest.cs
Sources/Runtime/Test.Psi/EmitterTester.cs
Sources/Speech/Microsoft.Psi.Speech.Windows/SystemSpeechIntentDetector.cs
Sources/Speech/Microsoft.Psi.Speech.Windows/SystemSpeechRecognizer.cs
Sources/Visualization/Microsoft.Psi.Visualization.Windows/Views/Visuals2D/DiagnosticsVisualization/PipelineDiagnosticsVisualizationPresenter.cs

- Fixed throttled delivery policies to be lossless.
- Added an adjustable throttling queue size threshold to DeliveryPolicies.
- Modified the HoloLensCapture exporter tool to use throttling with ReplayAll.
- Changed receivers to enforce isolation by default (change only affects synchronous execution).
- Removed the autoClone flag from CreateReceiver methods.

Various runtime changes affecting throttling and synchronous message delivery

---

Sources/MixedReality/HoloLensCapture/HoloLensCaptureApp/HoloLensCaptureApp.cs

- By default, don't encode infrared
- If encoding, only gzip is supported
- Also extended configuration options to include Ahat infrared images, separate from long-throw depth

Fixed HoloLens Capture App Bug when Encoding Infrared Images

---

Sources/Audio/Microsoft.Psi.Audio/Reframe.cs
Sources/MixedReality/HoloLensCapture/HoloLensCaptureExporter/DataExporter.cs
Sources/MixedReality/HoloLensCapture/HoloLensCaptureExporter/Readme.md
Sources/MixedReality/Microsoft.Psi.MixedReality.UniversalWindows/SceneUnderstanding.cs
Sources/MixedReality/Microsoft.Psi.MixedReality/Microphone.cs

`DataExporter`:
- Fixed a regression from previous PR that broke export of video and audio
- Refactored the code to isolate and speed up mpeg writing
- A start time for the mpeg is now also exported to a text file
Components:
- Added more checks to `Microphone` that it starts correctly and reads data as expected, otherwise throw exceptions
- `SceneUnderstanding` did not need to be an `IStepper`

Small changes to HoloLens microphone component and data export

---

Sources/Runtime/Microsoft.Psi/Persistence/InfiniteFileWriter.cs

When running out of disk space, the call to `MemoryMappedFile.CreateFromFile` throws the following exception: `System.IO.IOException: 'There is not enough space on the disk'`. The file handle still remains open in this case, and doesn't let other processes on the system delete/modify it.

fix: dispose the open file handle if disk is full

---

Sources/MixedReality/Microsoft.Psi.MixedReality.UniversalWindows/SpatialAnchorHelper.cs

These overloads coincide with the overloads for `SpatialAnchor.TryCreateRelativeTo` since they don't accept optional parameters as well.

Spatial Anchor overloads with position and rotation offsets

---

Sources/Runtime/Microsoft.Psi/Persistence/PsiStoreCommon.cs

For example, the store name of "recording" works well, but if you have a store called "recording (1)" then the whitespace character was not being properly escaped. Is this something you'd like done internally (e.g., this PR), or is it up to the caller to properly escape the store name string?

Enumerating store files doesn't match filenames with whitespace

---

Sources/Runtime/Microsoft.Psi/Common/Envelope.cs
Sources/Runtime/Microsoft.Psi/Data/IndexEntry.cs

Fixes #296 where auto struct layouts have changed in .NET 7

Make struct layouts explicit

---

Sources/Runtime/Test.Psi/PipelineTest.cs

- Increased diagnostic sampling interval to 10 ms

Made unit test more robust

---

Applications/Sigma/Sigma.sln

Both Microsoft.Psi.Speech.Windows and SigmaComputeServer rely on this project, so they fail to build on a fresh clone of the psi repo.
Simply adding Sources\Language\Microsoft.Psi.Language\Microsoft.Psi.Language.csproj to the solution (e.g. under the Dependencies folder) resolves this problem and allows the solution to build normally.
Closes #321

#321 Added Microsoft.Psi.Language project to Sigma.sln Dependencies
